export default {
	simple: [
		{ id: '1', type: 'input', label: 'Node 1', position: { x: 250, y: 5 } },
		{ id: '2', label: 'Node 2', position: { x: 100, y: 100 } },
		{ id: '3', label: 'Node 3', position: { x: 400, y: 100 } },
		{ id: '4', label: 'Node 4', position: { x: 400, y: 200 } },
		{ id: 'e1-2', source: '1', target: '2', animated: true },
		{ id: 'e1-3', source: '1', target: '3' },
	],
	horizontal: [
		{
			id: '1',
			type: 'input',
			label: 'Node 1',
			position: {
				x: 0,
				y: 50,
			},
			sourcePosition: 'right',
		},
		{
			id: '2',
			type: 'output',
			label: 'Node 2',
			position: {
				x: 250,
				y: 0,
			},
			targetPosition: 'left',
		},
		{
			id: '3',
			label: 'Node 3',
			position: {
				x: 250,
				y: 100,
			},
			sourcePosition: 'right',
			targetPosition: 'left',
		},
		{
			id: '4',
			label: 'Node 4',
			position: {
				x: 500,
				y: 150,
			},
			sourcePosition: 'right',
			targetPosition: 'left',
		},
		{
			id: '5',
			type: 'output',
			label: 'Node 5',
			position: {
				x: 750,
				y: 50,
			},
			sourcePosition: 'right',
			targetPosition: 'left',
		},
		{
			id: 'e1-2',
			source: '1',
			target: '2',
			animated: true,
		},
		{
			id: 'e1-3',
			source: '1',
			target: '3',
			markerEnd: 'arrow',
		},
		{
			id: 'e4-5',
			source: '4',
			target: '5',
			style: {
				stroke: 'orange',
			},
			labelBgStyle: {
				fill: 'orange',
			},
		},
		{
			id: 'e3-4',
			source: '3',
			target: '4',
		},
	],
	nested: [
		{ id: '1', type: 'input', handle: 'top', label: 'node', position: { x: 250, y: 0 } },
		{
			id: '2',
			label: 'parent node',
			position: { x: 100, y: 100 },
			style: { backgroundColor: 'rgba(16, 185, 129, 0.5)', width: '200px', height: '200px' },
		},
		{
			id: '2a',
			label: 'child node 1',
			position: { x: 10, y: 50 },
			parentNode: '2',
		},
		{
			id: '4',
			label: 'parent node 2',
			position: { x: 320, y: 175 },
			style: { backgroundColor: 'rgba(16, 185, 129, 0.5)', width: '400px', height: '300px' },
		},
		{
			id: '4a',
			label: 'child node 3',
			position: { x: 15, y: 65 },
			extent: 'parent',
			parentNode: '4',
		},
		{
			id: '4b',
			label: 'nested parent node',
			position: { x: 15, y: 120 },
			style: { backgroundColor: 'rgba(139, 92, 246, 0.5)', height: '150px', width: '270px' },
			parentNode: '4',
		},
		{
			id: '4b1',
			label: 'nested child node',
			position: { x: 20, y: 40 },
			parentNode: '4b',
		},
		{
			id: '4b2',
			label: 'nested child node',
			position: { x: 100, y: 100 },
			parentNode: '4b',
		},
		{ id: '4c', label: 'child node', position: { x: 200, y: 65 }, parentNode: '4' },
		{ id: 'e1-2', source: '1', target: '2', updatable: true },
		{ id: 'e1-4', source: '1', target: '4', updatable: true },
		{ id: 'e1-4c', source: '1', target: '4c', updatable: true },
		{ id: 'e2a-4a', source: '2a', target: '4a', updatable: true },
		{ id: 'e4a-4b1', source: '4a', target: '4b1', updatable: true },
		{ id: 'e4a-4b2', source: '4a', target: '4b2', updatable: true },
		{ id: 'e4b1-4b2', source: '4b1', target: '4b2', updatable: true },
	],
	label: [
		{
			type: 'input',
			dimensions: { width: 150, height: 41 },
			handleBounds: { source: [{ id: '1__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }] },
			computedPosition: { x: 45, y: 0, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '1',
			label: 'Start',
			position: { x: 45, y: 0 },
			style: { borderColor: '#10b981' },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '2__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '2__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 150, y: 105, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '2',
			label: 'Node 2',
			position: { x: 150, y: 105 },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '2a__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '2a__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 0, y: 180, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '2a',
			label: 'Node 2a',
			position: { x: 0, y: 180 },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '3__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '3__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 255, y: 195, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '3',
			label: 'Node 3',
			position: { x: 255, y: 195 },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '4__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '4__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 405, y: 300, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '4',
			label: 'Node 4',
			position: { x: 405, y: 300 },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '3a__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '3a__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 180, y: 300, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '3a',
			label: 'Node 3a',
			position: { x: 180, y: 300 },
		},
		{
			type: 'default',
			dimensions: { width: 150, height: 41 },
			handleBounds: {
				source: [{ id: '5__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
				target: [{ id: '5__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
			},
			computedPosition: { x: 195, y: 405, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '5',
			label: 'Node 5',
			position: { x: 195, y: 405 },
		},
		{
			type: 'output',
			dimensions: { width: 150, height: 41 },
			handleBounds: { target: [{ id: '6__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }] },
			computedPosition: { x: 0, y: 345, z: 0 },
			selected: false,
			dragging: false,
			resizing: false,
			initialized: true,
			data: {},
			events: {},
			id: '6',
			label: 'Output 6',
			position: { x: 0, y: 345 },
		},
		{
			type: 'default',
			source: '1',
			target: '2',
			data: {},
			events: {},
			label: 'bezier edge (default)',
			id: 'e1-2',
			class: 'normal-edge',
			sourceNode: {
				type: 'input',
				dimensions: { width: 150, height: 41 },
				handleBounds: { source: [{ id: '1__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }] },
				computedPosition: { x: 45, y: 0, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '1',
				label: 'Start',
				position: { x: 45, y: 0 },
				style: { borderColor: '#10b981' },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '2__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '2__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 150, y: 105, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '2',
				label: 'Node 2',
				position: { x: 150, y: 105 },
			},
			sourceX: 120,
			sourceY: 44,
			targetX: 225,
			targetY: 102,
		},
		{
			type: 'smoothstep',
			source: '2',
			target: '2a',
			data: {},
			events: {},
			label: 'smoothstep edge',
			id: 'e2-2a',
			sourceNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '2__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '2__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 150, y: 105, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '2',
				label: 'Node 2',
				position: { x: 150, y: 105 },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '2a__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '2a__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 0, y: 180, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '2a',
				label: 'Node 2a',
				position: { x: 0, y: 180 },
			},
			sourceX: 225,
			sourceY: 149,
			targetX: 75,
			targetY: 177,
		},
		{
			type: 'step',
			source: '2',
			target: '3',
			data: {},
			events: {},
			label: 'step edge',
			id: 'e2-3',
			sourceNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '2__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '2__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 150, y: 105, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '2',
				label: 'Node 2',
				position: { x: 150, y: 105 },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '3__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '3__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 255, y: 195, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '3',
				label: 'Node 3',
				position: { x: 255, y: 195 },
			},
			sourceX: 225,
			sourceY: 149,
			targetX: 330,
			targetY: 192,
		},
		{
			type: 'straight',
			source: '3',
			target: '4',
			data: {},
			events: {},
			label: 'straight edge',
			id: 'e3-4',
			sourceNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '3__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '3__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 255, y: 195, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '3',
				label: 'Node 3',
				position: { x: 255, y: 195 },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '4__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '4__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 405, y: 300, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '4',
				label: 'Node 4',
				position: { x: 405, y: 300 },
			},
			sourceX: 330,
			sourceY: 239,
			targetX: 480,
			targetY: 297,
		},
		{
			type: 'straight',
			source: '3',
			target: '3a',
			data: {},
			events: {},
			label: 'label only edge',
			id: 'e3-3a',
			style: { stroke: 'none' },
			sourceNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '3__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '3__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 255, y: 195, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '3',
				label: 'Node 3',
				position: { x: 255, y: 195 },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '3a__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '3a__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 180, y: 300, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '3a',
				label: 'Node 3a',
				position: { x: 180, y: 300 },
			},
			sourceX: 330,
			sourceY: 239,
			targetX: 255,
			targetY: 297,
		},
		{
			type: 'default',
			source: '4',
			target: '5',
			data: {},
			events: {},
			label: 'animated styled edge',
			id: 'e3-5',
			animated: true,
			style: { stroke: '#10b981' },
			sourceNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '4__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '4__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 405, y: 300, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '4',
				label: 'Node 4',
				position: { x: 405, y: 300 },
			},
			targetNode: {
				type: 'default',
				dimensions: { width: 150, height: 41 },
				handleBounds: {
					source: [{ id: '5__handle-bottom', position: 'bottom', x: 72, y: 38, width: 6, height: 6 }],
					target: [{ id: '5__handle-top', position: 'top', x: 72, y: -3, width: 6, height: 6 }],
				},
				computedPosition: { x: 195, y: 405, z: 0 },
				selected: false,
				dragging: false,
				resizing: false,
				initialized: true,
				data: {},
				events: {},
				id: '5',
				label: 'Node 5',
				position: { x: 195, y: 405 },
			},
			sourceX: 480,
			sourceY: 344,
			targetX: 270,
			targetY: 402,
		},
	],
} as {
	[key: string]: any[]
}
